### ISSUE TITLE
Not being able to run the server and client

### ISSUE THREAD

**Issue by AlainPlusPlus** [temmihoo/plushie-badname#3]
-Node version: 4.1.2

-This is the error log:
Error: Cannot find module 'clear'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/hellacio/Desktop/plushie-badname/server.js:11:21
    at Object.<anonymous> (/Users/hellacio/Desktop/plushie-badname/server.js:35:7)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by temmihoo** [comment]
The modules 'clear' and 'coap' are used but not put in requirements.

I'm not sure if clear should be gotten rid of or made a dev dependency by using it via a Gulp task or what. The jury is open. I'm perhaps partial to Gulp tasking.

The 'coap' should definitely be a dependency.

So, I'm suggesting a pull request changing Gulpfile.js and package.json to resolve this issue.

Meanwhile, a workaround is as follows:

npm install clear
npm install coap

**Comment by AlainPlusPlus** [comment]
Thanks! Yes, it works installing clear and coap. So, do you mean making 'coap' a submodule?

**Comment by temmihoo** [comment]
Good to hear it worked for you as well :)

The file package.json lists dependencies and tells npm if with installing plushie-badname some other modules are required. Adding 'coap' in there would make npm automatically install 'coap' whenever it installs the plushie-badname.
